### ISSUE TITLE
Yarn Workspace postinstall build error

### ISSUE THREAD

**Issue by egecavusoglu** [parcel-bundler/watcher#109]
I'm getting this error when a yarn workspace requires another peer workspace that has a `postinstall` script that uses `parcel build` in a Docker container.

Here's what I want to achieve:
1. Include other yarn workspaces as dependencies in package.json
2. Build these yarn workspace packages with parcel during `yarn install` with "postinstall" script (so that they're lazily built)

This approach works in M1 Mac, but fails in the Docker container with the following error.

```
#14 34.48 Command: yarn build
#14 34.48 Arguments: 
#14 34.48 Directory: /build/node_modules/@chember/express-helpers
#14 34.48 Output:
#14 34.48 yarn run v1.22.19
#14 34.48 $ parcel build
#14 34.48 Error: No native build was found for platform=linux arch=arm64 runtime=node abi=108 uv=1 armv=8 libc=glibc node=18.8.0
#14 34.48     loaded from: /build/node_modules/@parcel/watcher
#14 34.48 
#14 34.48     at load.path (/build/node_modules/node-gyp-build/index.js:60:9)
#14 34.48     at load (/build/node_modules/node-gyp-build/index.js:22:30)
#14 34.48     at Object.<anonymous> (/build/node_modules/@parcel/watcher/index.js:1:104)
#14 34.48     at Module._compile (/build/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
#14 34.48     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
#14 34.48     at Module.load (node:internal/modules/cjs/loader:997:32)
#14 34.48     at Module._load (node:internal/modules/cjs/loader:838:12)
#14 34.48     at Module.require (node:internal/modules/cjs/loader:1021:19)
#14 34.48     at require (/build/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
#14 34.48     at Object.<anonymous> (/build/node_modules/@parcel/fs/lib/index.js:7:28)
```

**Comment by devongovett** [comment]
Dup of #101
