### ISSUE TITLE
Windows - Could not find *.sln file. Did you run "configure"?

### ISSUE THREAD

**Issue by leopucci** [parcel-bundler/watcher#112]
Hi there. 
I am having trouble with windows build using node-gyp. 
For some reason it fails asking for *.sln file

```

gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp verb find Python - executing "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe" to get version
gyp verb find Python - version is "3.10.6"
gyp info find Python using Python version 3.10.6 found at "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp verb get node dir compiling against --target node version: 15.5.7
gyp verb command install [ '15.5.7' ]
gyp verb download using dist-url https://www.electronjs.org/headers
gyp verb install input version string "15.5.7"
gyp verb install installing version: 15.5.7
gyp verb install --ensure was passed, so won't reinstall if already installed
2022-10-03T13:41:22.701Z electron-rebuild failed to use prebuild-install: ExitCodeError: Command failed with a non-zero return code (1):
C:\Program Files\nodejs\node.exe C:\pkt\PocketDesktop\node_modules\electron-rebuild\lib\src\prebuild-shim.js C:\pkt\PocketDesktop\release\app\node_modules\better-sqlite3-multiple-ciphers\node_modules\prebuild-install\bin.js --arch=x64 --platform=win32 --tag-prefix=v --runtime=electron --target=15.5.7

Debugger listening on ws://127.0.0.1:50107/03952868-31ab-4b7f-b000-8fe9db40e1cd
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
    at ChildProcess.<anonymous> (C:\pkt\PocketDesktop\node_modules\electron-rebuild\node_modules\@malept\cross-spawn-promise\dist\src\index.js:101:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.cp.emit (C:\pkt\PocketDesktop\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1093:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:757:14) {
  cmd: 'C:\\Program Files\\nodejs\\node.exe',
  args: [
    'C:\\pkt\\PocketDesktop\\node_modules\\electron-rebuild\\lib\\src\\prebuild-shim.js',
    'C:\\pkt\\PocketDesktop\\release\\app\\node_modules\\better-sqlite3-multiple-ciphers\\node_modules\\prebuild-install\\bin.js',
    '--arch=x64',
    '--platform=win32',
    '--tag-prefix=v',
    '--runtime=electron',
    '--target=15.5.7'
  ],
  stdout: '',
  stderr: 'Debugger listening on ws://127.0.0.1:50107/03952868-31ab-4b7f-b000-8fe9db40e1cd\r\n' +
    'For help, see: https://nodejs.org/en/docs/inspector\r\n' +
    'Debugger attached.\r\n' +
    'Waiting for the debugger to disconnect...\r\n',
  code: 1
}
gyp verb install version is already installed, need to check "installVersion"
2022-10-03T13:41:22.703Z electron-rebuild rebuilding better-sqlite3-multiple-ciphers with args [
  'node',
  'node-gyp',
  'rebuild',
  '--runtime=electron',
  '--target=15.5.7',
  '--arch=x64',
  '--dist-url=https://www.electronjs.org/headers',
  '--build-from-source',
  '--verbose'
]
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.5.7
gyp verb build dir attempting to create "build" dir: C:\pkt\PocketDesktop\release\app\node_modules\@parcel\watcher\build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb command configure []
gyp verb download using dist-url https://www.electronjs.org/headers
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python checking Python explicitly set from environment variable PYTHON
gyp verb find Python - process.env.PYTHON is "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp verb find Python - executing "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe" to get executable path
gyp verb find Python - executable path is "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp verb find Python - executing "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe" to get version
gyp verb find Python - version is "3.10.6"
gyp info find Python using Python version 3.10.6 found at "C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
gyp verb get node dir compiling against --target node version: 15.5.7
gyp verb command install [ '15.5.7' ]
gyp verb download using dist-url https://www.electronjs.org/headers
gyp verb install input version string "15.5.7"
gyp verb install installing version: 15.5.7
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.5.7
gyp verb build dir attempting to create "build" dir: C:\pkt\PocketDesktop\release\app\node_modules\better-sqlite3-multiple-ciphers\build
gyp verb build dir "build" dir needed to be created? Yes
gyp verb find VS msvs_version not set from command line or npm config
gyp verb find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp verb find VS checking VS2022 (17.3.32922.545) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v143
gyp verb find VS - found Windows SDK: 10.0.22621.0
gyp info find VS using VS2022 (17.3.32922.545) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\pkt\PocketDesktop\release\app\node_modules\@parcel\watcher\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\pkt\PocketDesktop\release\app\node_modules\better-sqlite3-multiple-ciphers\config.gypi
gyp verb common.gypi checking for gypi file: C:\pkt\PocketDesktop\release\app\node_modules\better-sqlite3-multiple-ciphers\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\pkt\\PocketDesktop\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\pkt\\PocketDesktop\\release\\app\\node_modules\\@parcel\\watcher\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\pkt\\PocketDesktop\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\leo\\.electron-gyp\\15.5.7\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\leo\\.electron-gyp\\15.5.7',
gyp info spawn args   '-Dnode_gyp_dir=C:\\pkt\\PocketDesktop\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\leo\\\\.electron-gyp\\\\15.5.7\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\pkt\\PocketDesktop\\release\\app\\node_modules\\better-sqlite3-multiple-ciphers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\pkt\\PocketDesktop\\release\\app\\node_modules\\@parcel\\watcher\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb find VS checking VS2022 (17.3.32922.545) found at:
gyp verb find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp verb find VS - found "Visual Studio C++ core features"
gyp verb find VS - found VC++ toolset: v143
gyp verb find VS - found Windows SDK: 10.0.22621.0
gyp info find VS using VS2022 (17.3.32922.545) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\pkt\PocketDesktop\release\app\node_modules\better-sqlite3-multiple-ciphers\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\pkt\PocketDesktop\release\app\node_modules\better-sqlite3-multiple-ciphers\config.gypi
gyp verb common.gypi checking for gypi file: C:\pkt\PocketDesktop\release\app\node_modules\better-sqlite3-multiple-ciphers\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Users\leo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\pkt\\PocketDesktop\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\pkt\\PocketDesktop\\release\\app\\node_modules\\better-sqlite3-multiple-ciphers\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\pkt\\PocketDesktop\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\leo\\.electron-gyp\\15.5.7\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\leo\\.electron-gyp\\15.5.7',
gyp info spawn args   '-Dnode_gyp_dir=C:\\pkt\\PocketDesktop\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\leo\\\\.electron-gyp\\\\15.5.7\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\pkt\\PocketDesktop\\release\\app\\node_modules\\better-sqlite3-multiple-ciphers',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\pkt\\PocketDesktop\\release\\app\\node_modules\\better-sqlite3-multiple-ciphers\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build [ map: [Function (anonymous)] ]
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\leo\.electron-gyp\15.5.7
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild 'C:\pkt\PocketDesktop\release\app\node_modules\@parcel\watcher'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find *.sln file. Did you run "configure"?



Error: node-gyp failed to rebuild 'C:\pkt\PocketDesktop\release\app\node_modules\@parcel\watcher'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: Could not find *.sln file. Did you run "configure"?


    at NodeGyp.rebuildModule (C:\pkt\PocketDesktop\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:117:19)
    at async ModuleRebuilder.rebuildNodeGypModule (C:\pkt\PocketDesktop\node_modules\electron-rebuild\lib\src\module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (C:\pkt\PocketDesktop\node_modules\electron-rebuild\lib\src\module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (C:\pkt\PocketDesktop\node_modules\electron-rebuild\lib\src\rebuild.js:149:13)
    at async Promise.all (index 0)
    at async Rebuilder.rebuild (C:\pkt\PocketDesktop\node_modules\electron-rebuild\lib\src\rebuild.js:108:13)
    at async C:\pkt\PocketDesktop\node_modules\electron-rebuild\lib\src\cli.js:158:9
Waiting for the debugger to disconnect...
Error: Command failed: ..\..\node_modules\.bin\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .
    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at Object.<anonymous> (C:\pkt\PocketDesktop\.erb\scripts\electron-rebuild.js:17:11)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (C:\pkt\PocketDesktop\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (C:\pkt\PocketDesktop\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  status: 4294967295,
  signal: null,
  output: [ null, null, null ],
  pid: 8980,
  stdout: null,
  stderr: null
}
```

**Comment by leopucci** [comment]
$ node --version
v16.17.0
$ node-gyp --version
v9.1.0
npm --version
8.19.2

**Comment by leopucci** [comment]
solved formating machine and reinstalling everything
