### ISSUE TITLE
Error building parcel watcher on m1

### ISSUE THREAD

**Issue by SashvDave** [parcel-bundler/watcher#182]
Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-darwin-arm64. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.
    at Object.<anonymous> (/Users/sashvdave/Devon/electron/node_modules/@parcel/watcher/index.js:26:13)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/sashvdave/Devon/electron/.vite/build/main.js:28:17)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
2024-07-07 10:17:44.588 Electron[59663:2966073] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.

**Comment by oscareng** [comment]
have this same issue

**Comment by bharathvaj-ganesan** [comment]
+1. Facing this issue when bundling as a standalone executable using pkg.

**Comment by dezyh** [comment]
Just sharing on behalf of a coworker, we got the same error until rolling back to `v2.1.0`. This was the point in which the `prebuilds` binaries stopped being shipped with the package (as far as I can tell).
 - https://unpkg.com/browse/@parcel/watcher@2.1.0
 - https://unpkg.com/browse/@parcel/watcher@2.2.0-alpha.0

Adding the following the `package.json` was our workaround for this issue. 
```
  "overrides": {
    "@parcel/watcher": "~2.1.0"
  }
```

**Comment by devongovett** [comment]
`@parcel/watcher-darwin-arm64` does exist. So if it's not being installed then that's a problem with your package manager.
